### ISSUE TITLE
pymc.test() failure on MacOS 10.7.5

### ISSUE THREAD

**Issue by robertotrotta** [pymc-devs/pymc3#309]
Hi
I'm running the test suite on MacOS 10.7.5 and it hangs with this output:

pymc.test()
..K...Running unit tests for pymc.tests
NumPy version 1.7.1
NumPy is installed in /Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/numpy
Python version 2.7.3 | 64-bit | (default, Jun 14 2013, 18:17:36) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
nose version 1.2.1
Could not generate output statistics for. early_mean
Plotting early_mean
Plotting switchpoint
PlottingE..F...........S.............S..........

Plot windows are produced and they blink all the time -- no visible output is ever plotted.

**Comment by fonnesbeck** [comment]
Can you post the entire output from the tests (either here or to a gist)? I would have to see the actual errors to be able to reproduce and debug the problem. Which backend are you using?

**Comment by robertotrotta** [comment]
Here is the full output (I need to stop it with control-C as it hangs while plotting). I'm running Canopy 1.0.3.

Thanks!  

 pymc.test()
Running unit tests for pymc.tests
NumPy version 1.7.1..K.....
NumPy is installed in /Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/numpy
Python version 2.7.3 | 64-bit | (default, Jun 14 2013, 18:17:36) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
nose version 1.2.1
Plotting switchpoint
Plotting early_mean
Plotting..............S.............S.............................................................................................................. late_mean
Halting at iteration F............... 6978  of  10000

# 

## FAIL: test_simple (pymc.tests.test_missing.TestMissing)

Traceback (most recent call last):
  File "/Users/trotta/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pymc/tests/test_missing.py", line 34, in test_simple
    assert_equal(shape(tr), (5000, 2))
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/numpy/testing/utils.py", line 252, in assert_equal
    assert_equal(actual[k], desired[k], 'item=%r\n%s' % (k,err_msg), verbose)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/numpy/testing/utils.py", line 314, in assert_equal
    raise AssertionError(msg)
AssertionError:  
Items are not equal:
item=0

 ACTUAL: 1978
 DESIRED: 5000

---

Ran 162 tests in 98.949s

FAILED (KNOWNFAIL=1, SKIP=2, failures=1)
Out[49]: <nose.result.TextTestResult run=162 errors=0 failures=1>  

## 

Roberto Trotta

This message is confidential and is intended solely for the use of the individual(s) to whom it is addressed.

**Comment by fonnesbeck** [comment]
OK, thanks. That's an odd error. Are you using a PyMC that you built yourself, or one that ships with Canopy? We've fixed a lot of bugs since the 2.2 release. Do you know which backend is being used for the plots? You can try setting it explicitly:

```
import matplotlib
matplotlib.use('osx')
```

**Comment by robertotrotta** [comment]
I'm using the PyMC that comes with Canopy. It's v 2.2.0. How do I go about updating it?  

The plots setting does not work, returning the error:  

/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/**init**.py:1033: UserWarning:  This call to matplotlib.use() has no effect
because the the backend has already been chosen;
matplotlib.use() must be called _before_ pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

Thanks!  

## 

Roberto Trotta

This message is confidential and is intended solely for the use of the individual(s) to whom it is addressed.

**Comment by fonnesbeck** [comment]
Regarding the Matplotlib backend, if you can open your `~/.matplotlib/matplotibrc` file and see what the `backend` variable is set to, you might want to try configuring it this way:

```
backend      : MacOSX
```

Regarding the package version, you can try updating to the latest PyMC in GitHub by the following:

```
pip -U --no-deps git+git://github.com/pymc-devs/pymc.git
```

I'm not sure how restrictive Canopy is for updating packages externally (i.e. not from its package updater). If it does not work, I would not be too worried -- having only one failure isn't terrible. There aren't any show-stopper bugs in our 2.2 release.

**Comment by robertotrotta** [comment]
I'm still experiencing issues with the figure windows flickering in and out of existence and throwing up the wheel of death. I cannot locate the matplotlibrc file you indicated, all I get in the matplotlib directory is the following:  

trotta@parsnip:~/.matplotlib$ ls -al
total 216
drwxr-xr-x    4 trotta  staff     136 15 Jul 12:28 .
drwxr-xr-x+ 109 trotta  staff    3706 11 Jul 12:01 ..
-rw-r--r--    1 trotta  staff  108216  6 Jul 07:46 fontList.cache
drwxr-xr-x   12 trotta  staff     408  9 Jul 11:33 tex.cache

Thanks!  

Roberto  

## 

Roberto Trotta

This message is confidential and is intended solely for the use of the individual(s) to whom it is addressed.

**Comment by robertotrotta** [comment]
Here is an example of the kind of error I get when I terminate the frozen plot windows:  

Error in sys.excepthook:
Traceback (most recent call last):
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/IPython/core/ultratb.py", line 1029, in **call**
    self.handler((etype, evalue, etb))
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/IPython/core/ultratb.py", line 1020, in handler
    ostream.flush()
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 291, in resizeEvent
    self.draw()
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 148, in draw
    FigureCanvasAgg.draw(self)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 440, in draw
    self.figure.draw(self.renderer)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/figure.py", line 1006, in draw
    func(_args)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, *args, *_kwargs)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/axes.py", line 2086, in draw
    a.draw(renderer)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/axis.py", line 1064, in draw
    self.label.draw(renderer)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/text.py", line 531, in draw
    bbox, info = self._get_layout(renderer)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/text.py", line 313, in _get_layout
    ismath=ismath)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 205, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/mathtext.py", line 3010, in parse
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/mathtext.py", line 2344, in parse
    str(err)]))
ValueError:  
$lpha$ value
^
Expected end of text (at char 0), (line:1, col:1)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/IPython/core/ultratb.py", line 1029, in __call__
    self.handler((etype, evalue, etb))
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/IPython/core/ultratb.py", line 1020, in handler
    ostream.flush()
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 291, in resizeEvent
    self.draw()
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 148, in draw
    FigureCanvasAgg.draw(self)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 440, in draw
    self.figure.draw(self.renderer)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/figure.py", line 1006, in draw
    func(_args)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, *args, *_kwargs)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/axes.py", line 2086, in draw
    a.draw(renderer)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/axis.py", line 1064, in draw
    self.label.draw(renderer)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/artist.py", line 54, in draw_wrapper
    draw(artist, renderer, _args, *_kwargs)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/text.py", line 531, in draw
    bbox, info = self._get_layout(renderer)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/text.py", line 313, in _get_layout
    ismath=ismath)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 205, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/mathtext.py", line 3010, in parse
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/matplotlib/mathtext.py", line 2344, in parse
    str(err)]))
ValueError:  
$lpha$ value
^
Expected end of text (at char 0), (line:1, col:1)

## 

Roberto Trotta

This message is confidential and is intended solely for the use of the individual(s) to whom it is addressed.

**Comment by fonnesbeck** [comment]
Can you post the whole error output? I don't see any errors originating from PyMC in what you posted. Also, did you try updating PyMC using the pip commands that I posted above?

**Comment by fonnesbeck** [comment]
Were you able to obtain more information on this?
