### ISSUE TITLE
PyMC 2.3 Release

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc3#332]
I'd like to get a 2.3 release out the door so that folks stop using the 2.2 release. This should be the last release of 2.x, and should be straightforward. I''m going to try and close all the v.2 issues that I can, and discard or push others to v.3, as appropriate. Anyone who has favorites to be taken care of prior to this release, now is a good time to make me aware of them. 

And of course, anyone wishing to lend a hand is welcome to do so.

**Comment by fonnesbeck** [comment]
Once I deal with the AdaptiveMetropolis issue, we should be ready to roll out this release. I closed several issues which had no response for requests for info. Please add any other issues that you feel should be addressed in 2.3.

**Comment by fonnesbeck** [comment]
Tests now pass. I'm going to target Friday, 18 Oct. for the release, unless other issues arise.

**Comment by fonnesbeck** [comment]
Preparing to tag 2.3. Speak now.

**Comment by cdeil** [comment]
It seems that the 2.3 release is out?
https://pypi.python.org/pypi/pymc/2.3

That page doesn't mention if Python 3 is supported now or not!?
I get tons of test errors with Python 3.3: https://gist.github.com/cdeil/7258527
The PyPI page mentions this requirement `numpy (>=1.9)` which doesn't exist.

The docs still show 2.2 and also don't mention if Python 3 is supported:
http://pymc-devs.github.io/pymc/

**Comment by cdeil** [comment]
@fonnesbeck I think you did a "stealth upgrade" of a released tar ball?
This causes problems for packet managers because the checksum changes.
See point 2 at https://trac.macports.org/wiki/FAQ#checksums and https://trac.macports.org/ticket/35241#comment:10 specifically for the 2.3 release.

**Comment by fonnesbeck** [comment]
I don't think I did a stealth upgrade. I tagged a release on Github, and updated to 2.3 on PyPI. I will fix the numpy requirement. 

PyMC has worked with Python 3 since 2.2, so the errors  are new to me. I don't use Python 3 myself, but none of these have been reported. The HDF5 errors are due to HDF5 not being properly installed; the others are baffling.

**Comment by fonnesbeck** [comment]
PyMC 2.3 was moved off the master branch to a 2.3 branch, incase this caused any issues.

Happy to do a 2.3.1 bug fix release when we sort all this out.

**Comment by fonnesbeck** [comment]
I see what you mean about the stealth release. Sorry about that.

**Comment by cdeil** [comment]
@fonnesbeck I think the checksum of `pymc-2.3.tar.gz` changed again and broke the installation via Macports:

```
:info:checksum --->  Checksumming pymc-2.3.tar.gz
:error:checksum Checksum (rmd160) mismatch for pymc-2.3.tar.gz
:info:checksum Portfile checksum: pymc-2.3.tar.gz rmd160 91d3afc6197d683fcc556fcacc114c3b8639ae4e
:info:checksum Distfile checksum: pymc-2.3.tar.gz rmd160 8f810928bd2edf8fbd857eb08530e81d9a661028
:error:checksum Checksum (sha256) mismatch for pymc-2.3.tar.gz
:info:checksum Portfile checksum: pymc-2.3.tar.gz sha256 23b5a94fc282f6cece096962549cb972cc6c9760a0aa69dc49867bfe580f5688
:info:checksum Distfile checksum: pymc-2.3.tar.gz sha256 b4ce92cfffcdebfb4e4083bae5113b019b8ef2c33f3fd020d2818cc3a9a4b53d
:info:checksum The correct checksum line may be:
:info:checksum checksums           rmd160  8f810928bd2edf8fbd857eb08530e81d9a661028 \
                    sha256  b4ce92cfffcdebfb4e4083bae5113b019b8ef2c33f3fd020d2818cc3a9a4b53d
```

You can avoid this problem by never changing a released version and instead making a bug fix release (`2.3.x` in this case).

**Comment by cdeil** [comment]
Should I file a separate issue for the Python 3.3 test errors?
https://gist.github.com/cdeil/7258527

If you can't reproduce I can give you ssh access to a OS X 10.9 Mac to debug if you want.

**Comment by fonnesbeck** [comment]
I'm preparing a bug fix release 2.3.1. Will try to make it cleaner this time. Closing this issue; feel free to open one for the remaining bugs, if you find any.

**Comment by twiecki** [comment]
One thing that would help is a release candidate I think.

**Comment by fonnesbeck** [comment]
Good idea. [Done](https://github.com/pymc-devs/pymc/tree/2.3.1_rc1).
